"""GENERATED by tools/emit_product_guardrail.py in the canon repo. Do NOT hand-edit.

The vocabulary of the FLUID commercial offering, as enforced in the product
repos. The authority is `tools/canon.py`, which does not travel; this is the
publishable subset of it.

CANON_ID is a digest of these registries plus the semantics of the engine that
reads them. A hand-edit here — a widened regex, an extra name, a relaxed rule —
fails this repo's own CI, offline, on the pull request that made it. To change
the vocabulary, edit tools/canon.py in the canon repo and re-emit.

Emitted 2026-09-06.
"""

CANON_ID = '785922bbdc3f88d382141b7728d2b8a561fe38b7bf8bf5ff23b76a8abf4c9993'

# Approved names. Exact casing is part of the name. `near` matches the
# near-misses case-insensitively; anything it catches that is not the target
# spelling is a finding. `variants` marks the names where British and American
# spellings are both legitimate and the REPO decides which — the product ships
# en-US and the canon itself is en-GB.
APPROVED = [
    {
        'name': 'FLUID Fabric Ecosystem',
        'near': '\\bFLUID\\s+Fabric(\\s+Ecosystem)?\\b',
        'public_why': "The whole platform. The diagram's full title is 'The FLUID Fabric Ecosystem'; every name below is a part of it.",
        'must_flag': 'the Fluid fabric ecosystem ties it together',
        'must_not_flag': 'The FLUID Fabric Ecosystem ties it together',
    },
    {
        'name': 'FLUID Spec',
        'near': '\\bFLUID\\s+Spec(ification)?\\b',
        'public_why': "The open contract specification at the centre of the platform. Two words, both capitalised. Never 'FLUID Specification'.",
        'must_flag': 'the FLUID spec is the core',
        'must_not_flag': 'FLUID Spec is the core, and the FLUID standard is open',
    },
    {
        'name': 'Sovereignty Without Soil',
        'near': '\\b[Ss]overeignty\\s+[Ww]ithout\\s+[Ss]oil\\b',
        'public_why': 'The positioning phrase for running sovereign workloads without owning the ground they run on. Title Case, because it is a named idea.',
        'must_flag': 'sovereignty without soil is the point',
        'must_not_flag': 'Sovereignty Without Soil is the point',
    },
    {
        'name': 'Command Centre',
        'near': '\\bCommand\\s+Cent(er|re)\\b',
        'variants': {'en-GB': 'Command Centre', 'en-US': 'Command Center'},
        'public_why': 'The control plane: the web workbench where contracts, runs, catalogs and governance live. Two words, both capitalised.',
        'must_flag': 'the Command Center shows every contract',
        'must_not_flag': 'Command Centre shows every contract',
    },
    {
        'name': 'Business Simulation Lab',
        'near': '\\bBusiness\\s+Simulation\\s+Lab\\b|\\bBiz\\s*Lab\\b|\\bSimulation\\s+Lab\\b',
        'public_why': "The collaborative workshop environment inside the Command Center. Never 'Biz Lab', never bare 'Simulation Lab'.",
        'must_flag': 'the Biz Lab lets users assemble blueprints',
        'must_not_flag': 'the Business Simulation Lab lets users assemble blueprints',
    },
    {
        'name': 'FLUX Simulation Engine',
        'near': '\\bFLUX\\s+Simulat(ion\\s+Engine|or)\\b',
        'public_why': "The synthetic-data runtime. FLUX alone is the product name; the component is the FLUX Simulation Engine. Never 'FLUX Simulator'. Spec only today, so a present-tense capability claim is a finding.",
        'must_flag': 'the FLUX Simulator generates synthetic data',
        'must_not_flag': 'the FLUX Simulation Engine will generate synthetic data',
    },
    {
        'name': 'Outcome Optimiser',
        'near': '\\bOutcome\\s+Optimi[sz]er\\b',
        'variants': {'en-GB': 'Outcome Optimiser', 'en-US': 'Outcome Optimizer'},
        'public_why': 'Closes the loop between deployed data products and the business outcomes they were built to move.',
        'must_flag': 'the Outcome Optimizer tracks ROI',
        'must_not_flag': 'the Outcome Optimiser tracks ROI',
    },
    {
        'name': 'Data Product Factory',
        'near': '\\bData\\s+Product\\s+(Factory|Studio)\\b',
        'public_why': "The automated CI/CD pipeline around the Forge Engine. Never 'Data Product Studio'.",
        'must_flag': 'the Data Product Studio automates delivery',
        'must_not_flag': 'the Data Product Factory automates delivery',
    },
    {
        'name': 'Forge Engine',
        'near': '\\bForge\\s+(Engine|Compiler)\\b|\\bcontract[-\\s]+compiler\\b',
        'public_why': "The deterministic compiler from FLUID Spec to infrastructure. The CLI is `fluid`, the package is data-product-forge, the component is the Forge Engine. Never 'Forge Compiler' and never 'contract compiler' as a name — the verb ('one contract compiles to AWS') is fine.",
        'must_flag': 'the contract compiler turns YAML into infrastructure',
        'must_not_flag': 'the Forge Engine turns contracts into infrastructure; one contract compiles to AWS',
    },
    {
        'name': 'Computational Compliance',
        'near': '\\bComputational\\s+Compliance\\b',
        'public_why': 'Legal and security policy translated into executable code that runs with the data rather than beside it.',
        'must_flag': 'computational compliance is our moat',
        'must_not_flag': 'Computational Compliance is our moat',
    },
]

# Terms whose MEANING drifts even when the spelling is right. Documentation
# only — no rule reads these. Empty in this build: the maturity ledger is not published.
DEFINITIONS = [

]

# Dead names. A dead name coming back is the product-repo failure mode.
RETIRED = [
    {
        'id': 'fringe-as-product',
        'pattern': '\\bFRINGE\\b',
        'instead': 'the sovereign edge (runtime) / the sovereignty tier / Command Centre self-hosted',
        'allow': ['retire|superseded|predates|rename pending|was retired|do not reinstate|formerly branded'],
        'public_why': "FRINGE is a retired product name. The concept survives as 'the sovereign edge (runtime)' — the Command Center self-hosted at the network edge.",
        'must_flag': 'productises the certified rung as FRINGE, the sovereign edge runtime',
        'must_not_flag': 'the **FRINGE** product name was retired; do not reinstate',
    },
    {
        'id': 'ip-owned-by-pty-ltd',
        'pattern': 'Agentics Transformation Pty Ltd',
        'instead': 'Agentics Transformation Limited',
        'allow': ['resolved|RESOLVED|corrected|was either|attributed|predates|~~|DONE'],
        'public_why': "The company is Agentics Transformation Limited. 'Pty Ltd' is the wrong legal entity and must not survive in any published file — including site footers and container image labels.",
        'must_flag': 'Copyright 2024-2026 Agentics Transformation Pty Ltd',
        'must_not_flag': 'attributed copyright to Agentics Transformation Pty Ltd — RESOLVED, corrected in the published files',
    },
]

# Never approved in the first place. The only legal appearance is prose that
# quotes them in order to forbid them, which the allow-window covers.
NEVER_BRANDS = [
    {
        'name': 'FEDERATION',
        'pattern': '\\bFEDERATION\\b|\\bFederation\\s+(?:Hub|Registry|Center|Centre|Service|Platform|Manager|Console)\\b',
        'instead': 'the federation registry (descriptive, lowercase)',
        'allow': ['never a brand|not a brand|descriptive|forbid|retired'],
        'public_why': "Publishing contracts to a cross-org mesh is a capability, not a product. Write 'the federation registry', lowercase.",
        'must_flag': 'open the Federation Hub to browse shared contracts',
        'must_not_flag': "FEDERATION is never a brand; write 'the federation registry'",
    },
    {
        'name': 'FATHOM',
        'pattern': '\\bFATHOM\\b|\\bFathom\\s+(?:Engine|Service|Platform|Console|Manager)\\b',
        'instead': 'the settlement engine (descriptive, lowercase)',
        'allow': ['never a brand|not a brand|descriptive|forbid|retired'],
        'public_why': "Metering and billing for agent consumption is a capability, not a product. Write 'the settlement engine', lowercase.",
        'must_flag': 'the FATHOM Settlement Engine meters consumption',
        'must_not_flag': "FATHOM is never a brand; write 'the settlement engine'",
    },
    {
        'name': 'FORGE (standalone, all-caps)',
        'pattern': '\\bFORGE\\b(?!\\s*(Engine|Compiler))',
        'instead': 'Forge Engine (the component) / `fluid` (the CLI) / data-product-forge (the package)',
        'allow': ['never a brand|not a brand|unguarded|forbid|write instead|data-product-forge|rename|titled after|retired'],
        'public_why': "All-caps FORGE is not a product. Write 'Forge Engine' for the component, `fluid` for the CLI, data-product-forge for the package.",
        'must_flag': 'a mystical-looking compiler engine (FORGE) sits at the centre',
        'must_not_flag': 'all-caps FORGE was unguarded drift; write Forge Engine',
    },
]
